#! /bin/sh

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          5

bspc config active_border_color  \#202019
bspc config normal_border_color  \#202019
bspc config focused_border_color \#202019

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true


bspc rule -a Waterfox desktop='^1'
bspc rule -a Chromium desktop='^1'
bspc rule -a Telegram desktop='^2'
feh --bg-fill ~/pictures/wallpapers/wallpaper

if [ "$1" != "restart" ]; then
    sxhkd &
    waterfox &
    youtube &
    telegram &
    bar &
    xdo above -t $(xdo id -n root) $(xdo id -n lemonbar)
    xbindkeys -p &
fi

bspc rule -a Gimp state=floating follow=on
